
/*
CREATE TABLE `movies` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ID_MOVIE` int(11) NOT NULL,
    `YEAR_RELEASE` date NOT NULL,
    `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`ID_MOVIE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;
*/


CREATE TABLE `movies` (
    `ID_MOVIE` int(11) NOT NULL,
    `YEAR_RELEASE` varchar(4) NOT NULL,
    `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`ID_MOVIE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `training_sets` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `MOVIE_ID` int(11) NOT NULL,
    `USER_ID` int(11) NOT NULL,
    `RATING` int(11) NOT NULL,
    `DATE_RATING` date NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `searchs` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `ID_MOVIE_WEB` int(11) NOT NULL,
    `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
    `POPULARITY` float(7,6) NOT NULL,
    `ORIGINAL_TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
    `ORIGINAL_LANGUAGE` varchar(255) COLLATE utf8_bin NOT NULL,
    `ADULT` boolean NOT NULL,
    `RELEASE_DATE` date NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

CREATE TABLE `search_genres` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `SEARCH_ID` int(11) NOT NULL,
    `GENRE_ID` int(11) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;


CREATE TABLE `genres` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `TITLE` varchar(255) COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;

ALTER TABLE `training_sets` MODIFY COLUMN `MOVIE_ID` INT(11) NOT NULL,
 ADD CONSTRAINT movies_movie_id_fk
 FOREIGN KEY(MOVIE_ID)
 REFERENCES movies(ID_MOVIE);

ALTER TABLE `search_genres` MODIFY COLUMN `SEARCH_ID` INT(11) NOT NULL,
 ADD CONSTRAINT searchs_search_id_fk
 FOREIGN KEY(SEARCH_ID)
 REFERENCES searchs(ID);

ALTER TABLE `search_genres` MODIFY COLUMN `GENRE_ID` INT(11) NOT NULL,
 ADD CONSTRAINT genres_genre_id_fk
 FOREIGN KEY(GENRE_ID)
 REFERENCES genres(ID);